import type { Linter } from "eslint";
import type { CommonOptions } from "./perfectionist-rules/common/CommonOptions.ts";
import type { Rules } from "./Rules.ts";

const builtinModules = [
    "_http_agent",
    "_http_client",
    "_http_common",
    "_http_incoming",
    "_http_outgoing",
    "_http_server",
    "_stream_duplex",
    "_stream_passthrough",
    "_stream_readable",
    "_stream_transform",
    "_stream_wrap",
    "_stream_writable",
    "_tls_common",
    "_tls_wrap",
    "assert",
    "assert/strict",
    "async_hooks",
    "buffer",
    "child_process",
    "cluster",
    "console",
    "constants",
    "crypto",
    "dgram",
    "diagnostics_channel",
    "dns",
    "dns/promises",
    "domain",
    "events",
    "fs",
    "fs/promises",
    "http",
    "http2",
    "https",
    "inspector",
    "inspector/promises",
    "module",
    "net",
    "os",
    "path",
    "path/posix",
    "path/win32",
    "perf_hooks",
    "process",
    "punycode",
    "querystring",
    "readline",
    "readline/promises",
    "repl",
    "stream",
    "stream/consumers",
    "stream/promises",
    "stream/web",
    "string_decoder",
    "sys",
    "timers",
    "timers/promises",
    "tls",
    "trace_events",
    "tty",
    "url",
    "util",
    "util/types",
    "v8",
    "vm",
    "wasi",
    "worker_threads",
    "zlib",
];

/**
 * Rules that detect things that are highly likely to be errors
 */
const errorDetection = {
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/consistent-type-exports": [
        "error",
        { fixMixedExportsWithInlineTypeSpecifier: true },
    ],
    "@typescript-eslint/no-array-constructor": "error",
    "@typescript-eslint/no-array-delete": "error",
    "@typescript-eslint/no-base-to-string": [
        "error",
        {
            checkUnknown: true,
        },
    ],
    "@typescript-eslint/no-confusing-non-null-assertion": "error",
    "@typescript-eslint/no-confusing-void-expression": [
        "error",
        {
            ignoreArrowShorthand: false,
            ignoreVoidOperator: true,
        },
    ],
    "@typescript-eslint/no-duplicate-enum-values": "error",
    "@typescript-eslint/no-empty-object-type": [
        "error",
        {
            allowInterfaces: "always",
            allowObjectTypes: "never",
        },
    ],
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-floating-promises": [
        "error",
        {
            ignoreIIFE: false,
            ignoreVoid: true,
        },
    ],
    "@typescript-eslint/no-for-in-array": "error",
    "@typescript-eslint/no-implied-eval": "error",
    "@typescript-eslint/no-misused-promises": [
        "error",
        {
            checksConditionals: true,
            checksVoidReturn: true,
        },
    ],
    "@typescript-eslint/no-mixed-enums": "error",
    "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-redundant-type-constituents": "error",
    "@typescript-eslint/no-unsafe-argument": "error",
    "@typescript-eslint/no-unsafe-assignment": "error",
    "@typescript-eslint/no-unsafe-call": "error",
    "@typescript-eslint/no-unsafe-declaration-merging": "error",
    "@typescript-eslint/no-unsafe-member-access": "error",
    "@typescript-eslint/no-unsafe-return": "error",
    "@typescript-eslint/no-unsafe-unary-minus": "error",
    "@typescript-eslint/no-unused-expressions": [
        "error",
        {
            allowShortCircuit: true,
            allowTaggedTemplates: true,
            allowTernary: false,
        },
    ],
    "@typescript-eslint/no-unused-vars": [
        "error",
        {
            argsIgnorePattern: "^",
            caughtErrors: "all",
            ignoreRestSiblings: true,
            varsIgnorePattern: "^_",
        },
    ],
    "@typescript-eslint/prefer-namespace-keyword": "error",
    "@typescript-eslint/require-array-sort-compare": [
        "error",
        {
            ignoreStringArrays: true,
        },
    ],
    "@typescript-eslint/restrict-plus-operands": "error",
    "@typescript-eslint/restrict-template-expressions": [
        "error",
        {
            allowAny: false,
            allowBoolean: true,
            allowNullish: false,
            allowNumber: true,
            allowRegExp: false,
        },
    ],
    "@typescript-eslint/strict-boolean-expressions": [
        "error",
        {
            allowAny: true,
            allowNullableBoolean: true,
            allowNullableNumber: false,
            allowNullableObject: true,
            allowNullableString: false,
            allowNumber: false,
            allowString: false,
        },
    ],
    "@typescript-eslint/switch-exhaustiveness-check": "error",
    "@typescript-eslint/unbound-method": [
        "error",
        {
            ignoreStatic: false,
        },
    ],
    "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
    curly: ["error", "multi-line"],
    eqeqeq: [
        "error",
        "always",
        {
            null: "ignore",
        },
    ],
    "for-direction": "error",
    "no-case-declarations": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-constant-condition": [
        "error",
        {
            checkLoops: false,
        },
    ],
    "no-delete-var": "error",
    "no-dupe-args": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty-character-class": "error",
    "no-extra-bind": "error",
    "no-fallthrough": [
        "error",
        {
            commentPattern: "^continue$",
        },
    ],
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-misleading-character-class": ["error", { allowEscape: true }],
    "no-multi-assign": "error",
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-promise-executor-return": "error",
    "no-prototype-builtins": "error",
    "no-regex-spaces": "error",
    "no-return-assign": "error",
    "no-self-assign": [
        "error",
        {
            props: true,
        },
    ],
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "error",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "error",
    "no-unreachable": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": [
        "error",
        {
            disallowArithmeticOperators: true,
        },
    ],
    "no-unused-labels": "error",
    "no-useless-backreference": "error",
    "no-useless-call": "error",
    "no-useless-catch": "error",
    "no-useless-concat": "error",
    "no-useless-escape": "error",
    radix: ["error", "always"],
    "use-isnan": "error",
} satisfies Partial<Rules>;

/**
 * Rules that detect things that are likely to be problematic
 */
const codeHealth = {
    "@typescript-eslint/ban-ts-comment": [
        "error",
        {
            "ts-check": true,
            "ts-expect-error": false,
            "ts-ignore": true,
            "ts-nocheck": true,
        },
    ],
    "@typescript-eslint/ban-tslint-comment": "error",
    "@typescript-eslint/consistent-return": "error",
    "@typescript-eslint/consistent-type-assertions": [
        "error",
        {
            arrayLiteralTypeAssertions: "never",
            assertionStyle: "as",
            objectLiteralTypeAssertions: "never",
        },
    ],
    "@typescript-eslint/default-param-last": "error",
    "@typescript-eslint/explicit-function-return-type": [
        "error",
        {
            allowConciseArrowFunctionExpressionsStartingWithVoid: true,
            allowDirectConstAssertionInArrowFunctions: true,
            allowExpressions: true,
            allowHigherOrderFunctions: true,
            allowIIFEs: true,
            allowTypedFunctionExpressions: true,
        },
    ],
    "@typescript-eslint/explicit-module-boundary-types": [
        "error",
        {
            allowArgumentsExplicitlyTypedAsAny: true,
            allowDirectConstAssertionInArrowFunctions: true,
            allowHigherOrderFunctions: true,
            allowOverloadFunctions: true,
            allowTypedFunctionExpressions: true,
        },
    ],
    "@typescript-eslint/no-dupe-class-members": "error",
    "@typescript-eslint/no-extra-non-null-assertion": "error",
    "@typescript-eslint/no-import-type-side-effects": "error",
    "@typescript-eslint/no-invalid-void-type": [
        "error",
        {
            allowAsThisParameter: true,
            allowInGenericTypeArguments: true,
        },
    ],
    "@typescript-eslint/no-misused-spread": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-require-imports": "error",
    "@typescript-eslint/no-unnecessary-boolean-literal-compare": [
        "error",
        {
            allowComparingNullableBooleansToFalse: true,
            allowComparingNullableBooleansToTrue: true,
        },
    ],
    "@typescript-eslint/no-unnecessary-template-expression": "error",
    "@typescript-eslint/no-unnecessary-type-arguments": "error",
    "@typescript-eslint/no-unnecessary-type-assertion": "error",
    "@typescript-eslint/no-unnecessary-type-constraint": "error",
    "@typescript-eslint/no-unnecessary-type-conversion": "error",
    "@typescript-eslint/no-unnecessary-type-parameters": "error",
    "@typescript-eslint/no-unsafe-enum-comparison": "error",
    "@typescript-eslint/no-unsafe-function-type": "error",
    "@typescript-eslint/no-unsafe-type-assertion": "error",
    "@typescript-eslint/no-unused-private-class-members": "error",
    "@typescript-eslint/no-var-requires": "error",
    "@typescript-eslint/no-wrapper-object-types": "error",
    "@typescript-eslint/only-throw-error": "error",
    "@typescript-eslint/prefer-enum-initializers": "error",
    "@typescript-eslint/prefer-find": "error",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-literal-enum-member": "error",
    "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        {
            ignoreBooleanCoercion: true,
            ignoreConditionalTests: true,
            ignoreMixedLogicalExpressions: true,
        },
    ],
    "@typescript-eslint/prefer-optional-chain": "error",
    "@typescript-eslint/prefer-promise-reject-errors": ["error", { allowThrowingUnknown: true }],
    "@typescript-eslint/prefer-readonly": "error",
    "@typescript-eslint/prefer-reduce-type-parameter": "error",
    "@typescript-eslint/prefer-return-this-type": "error",
    "@typescript-eslint/prefer-string-starts-ends-with": "error",
    "@typescript-eslint/prefer-ts-expect-error": "error",
    "@typescript-eslint/related-getter-setter-pairs": "error",
    "@typescript-eslint/return-await": ["error", "always"],
    "@typescript-eslint/triple-slash-reference": [
        "error",
        {
            lib: "always",
            path: "never",
            types: "never",
        },
    ],
    "accessor-pairs": [
        "error",
        {
            enforceForClassMembers: true,
            getWithoutSet: false,
            setWithoutGet: true,
        },
    ],
    "default-case": "error",
    "import/no-absolute-path": [
        "error",
        {
            commonjs: true,
            esmodule: true,
        },
    ],
    "import/no-anonymous-default-export": [
        "error",
        {
            allowAnonymousClass: false,
            allowAnonymousFunction: false,
            allowArray: false,
            allowArrowFunction: false,
            allowCallExpression: false,
            allowLiteral: false,
            allowObject: false,
        },
    ],
    "max-statements-per-line": [
        "error",
        {
            max: 1,
        },
    ],
    "no-alert": "error",
    "no-class-assign": "error",
    "no-console": "error",
    "no-debugger": "error",
    "no-empty-pattern": "error",
    "no-eval": "error",
    "no-ex-assign": "error",
    "no-extend-native": "error",
    "no-label-var": "error",
    "no-lone-blocks": "error",
    "no-loss-of-precision": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-plusplus": [
        "error",
        {
            allowForLoopAfterthoughts: true,
        },
    ],
    "no-proto": "error",
    "no-unneeded-ternary": [
        "error",
        {
            defaultAssignment: false,
        },
    ],
    "no-useless-return": "error",
    "no-var": "error",
    "no-warning-comments": [
        "error",
        {
            terms: ["CRITICAL"],
        },
    ],
    "no-with": "error",
    "prefer-named-capture-group": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-regex-literals": [
        "error",
        {
            disallowRedundantWrapping: true,
        },
    ],
    "prefer-rest-params": "error",
    "require-unicode-regexp": [
        "error",
        {
            // TODO: Update this when TypeScript supports v flag
            requireFlag: "v",
        },
    ],
} satisfies Partial<Rules>;

/**
 * Rules that enforce certain stylistic consistency even if either form would be otherwise valid
 * NOTE: This does not include syntatic formatting rules, specifically rules belong here if they
 * correspond to different AST's
 */
const consistency = {
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/array-type": [
        "error",
        {
            default: "generic",
            readonly: "generic",
        },
    ],
    "@typescript-eslint/consistent-generic-constructors": ["error", "constructor"],
    "@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
    "@typescript-eslint/consistent-type-imports": [
        "error",
        {
            disallowTypeAnnotations: true,
            fixStyle: "separate-type-imports",
            prefer: "type-imports",
        },
    ],
    "@typescript-eslint/dot-notation": [
        "error",
        {
            allowKeywords: true,
        },
    ],
    "@typescript-eslint/no-duplicate-type-constituents": "error",
    "@typescript-eslint/no-empty-function": "error",
    "@typescript-eslint/no-restricted-imports": [
        "error",
        {
            paths: builtinModules.map((modName) => {
                const message = `Use node:${modName} instead`;
                return {
                    message,
                    name: modName,
                };
            }),
        },
    ],
    "@typescript-eslint/no-useless-constructor": "error",
    "@typescript-eslint/no-useless-empty-export": "error",
    "@typescript-eslint/parameter-properties": [
        "error",
        {
            prefer: "class-property",
        },
    ],
    "@typescript-eslint/prefer-as-const": "error",
    "@typescript-eslint/prefer-destructuring": [
        "error",
        {
            array: false,
            object: true,
        },
        {
            enforceForRenamedProperties: false,
        },
    ],
    "@typescript-eslint/prefer-function-type": "error",
    "@typescript-eslint/prefer-includes": "error",

    "default-case-last": "error",
    "func-names": ["error", "as-needed", {}],
    "func-style": [
        "error",
        "declaration",
        {
            allowArrowFunctions: true,
        },
    ],
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
    "import/first": "error",
    "import/newline-after-import": [
        "error",
        {
            count: 1,
        },
    ],
    "import/no-duplicates": [
        "error",
        {
            considerQueryString: false,
            "prefer-inline": false,
        },
    ],
    "import/no-empty-named-blocks": "error",
    "import/no-named-default": "error",
    "import/no-useless-path-segments": [
        "error",
        {
            commonjs: true,
            noUselessIndex: false,
        },
    ],
    "logical-assignment-operators": [
        "error",
        "always",
        {
            enforceForIfStatements: true,
        },
    ],
    "new-parens": ["error", "always"],
    "no-else-return": [
        "error",
        {
            allowElseIf: true,
        },
    ],
    "no-empty": [
        "error",
        {
            allowEmptyCatch: false,
        },
    ],
    "no-empty-static-block": "error",
    "no-extra-boolean-cast": [
        "error",
        {
            enforceForInnerExpressions: false,
        },
    ],
    "no-extra-label": "error",
    "no-floating-decimal": "error",
    "no-implicit-coercion": [
        "error",
        {
            boolean: true,
            disallowTemplateShorthand: false,
            number: true,
            string: true,
        },
    ],
    "no-inline-comments": "error",
    "no-lonely-if": "error",
    "no-negated-condition": "error",
    "no-useless-computed-key": [
        "error",
        {
            enforceForClassMembers: true,
        },
    ],
    "no-useless-rename": [
        "error",
        {
            ignoreDestructuring: false,
            ignoreExport: false,
            ignoreImport: false,
        },
    ],
    "object-shorthand": ["error", "always", {}],
    "one-var": ["error", "never"],
    "one-var-declaration-per-line": ["error", "initializations"],
    "operator-assignment": ["error", "always"],
    "prefer-arrow-callback": [
        "error",
        {
            allowNamedFunctions: true,
            allowUnboundThis: true,
        },
    ],
    "prefer-const": [
        "error",
        {
            destructuring: "any",
        },
    ],
    "prefer-exponentiation-operator": "error",
    "prefer-object-spread": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
} satisfies Partial<Rules>;

/**
 * Deprecated eslint rules
 * NOTE: As per https://typescript-eslint.io/linting/troubleshooting/formatting all style rules
 * are now off
 */
const deprecated = {
    "@typescript-eslint/brace-style": "off",
    "@typescript-eslint/comma-dangle": "off",
    "@typescript-eslint/comma-spacing": "off",
    "@typescript-eslint/func-call-spacing": "off",
    "@typescript-eslint/indent": "off",
    "@typescript-eslint/keyword-spacing": "off",
    "@typescript-eslint/lines-between-class-members": "off",
    "@typescript-eslint/member-delimiter-style": "off",
    "@typescript-eslint/no-extra-parens": "off",
    "@typescript-eslint/quotes": "off",
    "@typescript-eslint/semi": "off",
    "@typescript-eslint/space-before-blocks": "off",
    "@typescript-eslint/space-before-function-paren": "off",
    "@typescript-eslint/space-infix-ops": "off",
    "@typescript-eslint/type-annotation-spacing": "off",
    "array-bracket-newline": "off",
    "array-bracket-spacing": "off",
    "array-element-newline": "off",
    "arrow-parens": "off",
    "arrow-spacing": "off",
    "block-spacing": "off",
    "callback-return": "off",
    "comma-style": "off",
    "computed-property-spacing": "off",
    "dot-location": "off",
    "eol-last": "off",
    "function-call-argument-newline": "off",
    "function-paren-newline": "off",
    "generator-star-spacing": "off",
    "global-require": "off",
    "handle-callback-err": "off",
    "id-blacklist": "off",
    "implicit-arrow-linebreak": "off",
    "indent-legacy": "off",
    "jsx-quotes": "off",
    "key-spacing": "off",
    "line-comment-position": "off",
    "linebreak-style": "off",
    "lines-around-comment": "off",
    "lines-around-directive": "off",
    "max-len": "off",
    "newline-after-var": "off",
    "newline-before-return": "off",
    "newline-per-chained-call": "off",
    "no-buffer-constructor": "off",
    "no-catch-shadow": "off",
    "no-irregular-whitespace": "off",
    "no-mixed-requires": "off",
    "no-mixed-spaces-and-tabs": "off",
    "no-multi-spaces": "off",
    "no-multiple-empty-lines": "off",
    "no-native-reassign": "off",
    "no-negated-in-lhs": "off",
    "no-new-require": "off",
    "no-path-concat": "off",
    "no-process-env": "off",
    "no-process-exit": "off",
    "no-restricted-modules": "off",
    "no-spaced-func": "off",
    "no-sync": "off",
    "no-tabs": "off",
    "no-trailing-spaces": "off",
    "no-unused-private-class-members": "off",
    "no-whitespace-before-property": "off",
    "nonblock-statement-body-position": "off",
    "object-curly-newline": "off",
    "object-property-newline": "off",
    "operator-linebreak": "off",
    "padded-blocks": "off",
    "prefer-reflect": "off",
    "quote-props": "off",
    "rest-spread-spacing": "off",
    "semi-spacing": "off",
    "semi-style": "off",
    "space-in-parens": "off",
    "space-unary-ops": "off",
    "spaced-comment": "off",
    "switch-colon-spacing": "off",
    "template-curly-spacing": "off",
    "template-tag-spacing": "off",
    "unicode-bom": "off",
    "yield-star-spacing": "off",
} satisfies Partial<Rules>;

/**
 * Rules that TypeScript itself is able to cover
 */
const coveredByTypescript = {
    "@typescript-eslint/init-declarations": "off",
    "@typescript-eslint/no-invalid-this": "off",
    "constructor-super": "off",
    "getter-return": "off",
    "import/default": "off",
    "import/export": "off",
    "import/extensions": "off",
    "import/named": "off",
    "import/namespace": "off",
    "import/no-amd": "off",
    "import/no-commonjs": "off",
    "import/no-deprecated": "off",
    "import/no-extraneous-dependencies": "off",
    "import/no-import-module-exports": "off",
    "import/no-named-as-default": "off",
    "import/no-named-as-default-member": "off",
    "import/no-nodejs-modules": "off",
    "import/no-unresolved": "off",
    "import/unambiguous": "off",
    "init-declarations": "off",
    "new-cap": "off",
    "no-async-promise-executor": "off",
    "no-caller": "off",
    "no-const-assign": "off",
    "no-eq-null": "off",
    "no-global-assign": "off",
    "no-invalid-this": "off",
    "no-obj-calls": "off",
    "no-this-before-super": "off",
    "no-undef": "off",
    "no-undefined": "off",
    "no-use-before-define": "off",
} satisfies Partial<Linter.RulesRecord>;

/**
 * Rules that are covered by a different plugin
 */
const coveredByOtherPlugins = {
    "brace-style": "off",
    camelcase: "off",
    "comma-dangle": "off",
    "comma-spacing": "off",
    "consistent-return": "off",
    "default-param-last": "off",
    "dot-notation": "off",
    "func-call-spacing": "off",
    "import/order": [
        "off",
        {
            alphabetize: {
                caseInsensitive: true,
                order: "asc",
            },
        },
    ],
    indent: "off",
    "keyword-spacing": "off",
    "lines-between-class-members": "off",
    "no-array-constructor": "off",
    "no-dupe-class-members": "off",
    // Covered by other plugins
    "no-duplicate-imports": "off",
    "no-empty-function": "off",
    "no-extra-parens": "off",
    "no-extra-semi": "off",
    "no-implied-eval": "off",
    "no-loop-func": "off",
    "no-redeclare": "off",
    "no-underscore-dangle": "off",
    "no-unused-expressions": "off",
    "no-unused-vars": "off",
    "no-useless-constructor": "off",
    "object-curly-spacing": "off",
    quotes: "off",
    semi: "off",
    "sort-imports": [
        "off",
        {
            allowSeparatedGroups: true,
            ignoreCase: true,
            ignoreDeclarationSort: true,
            ignoreMemberSort: false,
        },
    ],
    "space-before-function-paren": "off",
    "space-infix-ops": "off",
} satisfies Partial<Linter.RulesRecord>;

const disabled = {
    "@typescript-eslint/class-literal-property-style": "off",
    "@typescript-eslint/class-methods-use-this": "off",
    "@typescript-eslint/consistent-type-definitions": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/member-ordering": "off",
    "@typescript-eslint/method-signature-style": "off",
    "@typescript-eslint/naming-convention": "off",
    "@typescript-eslint/no-dynamic-delete": "off",
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/no-extraneous-class": "off",
    "@typescript-eslint/no-inferrable-types": "off",
    "@typescript-eslint/no-loop-func": "off",
    "@typescript-eslint/no-magic-numbers": "off",
    "@typescript-eslint/no-meaningless-void-operator": "off",
    "@typescript-eslint/no-misused-new": "off",
    "@typescript-eslint/no-namespace": "off",
    "@typescript-eslint/no-redeclare": "off",
    "@typescript-eslint/no-restricted-types": "off",
    "@typescript-eslint/no-shadow": "off",
    "@typescript-eslint/no-this-alias": "off",
    "@typescript-eslint/no-type-alias": "off",
    "@typescript-eslint/no-unnecessary-parameter-property-assignment": "off",
    "@typescript-eslint/no-unnecessary-qualifier": "off",
    "@typescript-eslint/no-use-before-define": "off",
    "@typescript-eslint/non-nullable-type-assertion-style": "off",
    "@typescript-eslint/padding-line-between-statements": "off",
    "@typescript-eslint/prefer-regexp-exec": "off",
    "@typescript-eslint/promise-function-async": "off",
    "@typescript-eslint/require-await": "off",
    "@typescript-eslint/sort-type-constituents": "off",
    "@typescript-eslint/typedef": "off",
    "@typescript-eslint/unified-signatures": "off",
    "array-callback-return": "off",
    "arrow-body-style": "off",
    "block-scoped-var": "off",
    "capitalized-comments": "off",
    "class-methods-use-this": "off",
    complexity: "off",
    "consistent-this": "off",
    "func-name-matching": "off",
    "guard-for-in": "off",
    "id-denylist": "off",
    "id-length": "off",
    "id-match": "off",
    "import/dynamic-import-chunkname": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/no-cycle": "off",
    "import/no-default-export": "off",
    "import/no-dynamic-require": "off",
    "import/no-internal-modules": "off",
    "import/no-mutable-exports": "off",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-relative-packages": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-restricted-paths": "off",
    "import/no-self-import": "off",
    "import/no-unassigned-import": "off",
    "import/no-unused-modules": "off",
    "import/no-webpack-loader-syntax": "off",
    "import/prefer-default-export": "off",
    "max-classes-per-file": "off",
    "max-depth": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-nested-callbacks": "off",
    "max-params": "off",
    "max-statements": "off",
    "multiline-comment-style": ["off", "starred-block"],
    "multiline-ternary": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-confusing-arrow": "off",
    "no-constant-binary-expression": "off",
    "no-constructor-return": "off",
    "no-continue": "off",
    "no-control-regex": "off",
    "no-div-regex": "off",
    "no-extra-semi": "off",
    "no-implicit-globals": "off",
    "no-inner-declarations": "off",
    "no-iterator": "off",
    "no-labels": "off",
    "no-magic-numbers": "off",
    "no-mixed-operators": "off",
    "no-nested-ternary": "off",
    "no-new-symbol": "off",
    "no-param-reassign": "off",
    "no-restricted-exports": "off",
    "no-restricted-globals": "off",
    "no-restricted-imports": "off",
    "no-restricted-properties": "off",
    "no-restricted-syntax": "off",
    "no-return-await": "off",
    "no-script-url": "off",
    "no-shadow": "off",
    "no-shadow-restricted-names": "off",
    "no-template-curly-in-string": "off",
    "no-ternary": "off",
    "no-throw-literal": "off",
    "no-unassigned-vars": "off",
    "no-undef-init": "off",
    "no-void": "off",
    "padding-line-between-statements": "off",
    "prefer-destructuring": "off",
    "prefer-promise-reject-errors": "off",
    "require-atomic-updates": "off",
    "require-await": "off",
    "require-yield": "off",
    "sort-keys": "off",
    "sort-vars": "off",
    "space-before-blocks": "off",
    strict: "off",
    "symbol-description": "off",
    "valid-typeof": "off",
    "vars-on-top": "off",
    "wrap-iife": "off",
    "wrap-regex": "off",
    yoda: "off",
} satisfies Partial<Rules>;

const considerInFuture = {
    // Annoying for exhaustion in if-then chains
    "@typescript-eslint/no-unnecessary-condition": [
        "off",
        {
            allowConstantLoopConditions: "only-allowed-literals",
        },
    ],
    // Consider in future
    "@typescript-eslint/prefer-readonly-parameter-types": [
        "off",
        {
            checkParameterProperties: true,
            ignoreInferredTypes: true,
            treatMethodsAsReadonly: true,
        },
    ],
    "no-useless-assignment": "off",
    "preserve-caught-error": "off",
} satisfies Partial<Rules>;

const commonOptions: CommonOptions = {
    fallbackSort: { type: "alphabetical" },
    ignoreCase: true,
    type: "natural",
};

const perfectionistRules = {
    "perfectionist/sort-array-includes": ["error", commonOptions],
    "perfectionist/sort-classes": [
        "off",
        {
            ...commonOptions,
            groups: [
                // todo: figure these groups out
            ],
            type: "unsorted",
        },
    ],
    "perfectionist/sort-decorators": "off",
    "perfectionist/sort-enums": ["error", { ...commonOptions, sortByValue: true }],
    "perfectionist/sort-exports": ["error", commonOptions],
    "perfectionist/sort-heritage-clauses": ["error", commonOptions],
    "perfectionist/sort-imports": [
        "error",
        {
            ...commonOptions,
            newlinesBetween: 0,
        },
    ],
    "perfectionist/sort-interfaces": [
        "error",
        {
            groups: ["index-signature", "property", "method"],
            type: "unsorted",
        },
    ],
    "perfectionist/sort-intersection-types": [
        "error",
        {
            ...commonOptions,
            groups: [
                "conditional",
                "function",
                "import",
                "intersection",
                "keyword",
                "literal",
                "named",
                "object",
                "operator",
                "tuple",
                "union",
                "nullish",
            ],
        },
    ],
    "perfectionist/sort-jsx-props": ["error", commonOptions],
    "perfectionist/sort-maps": ["error", commonOptions],
    "perfectionist/sort-modules": "off",
    "perfectionist/sort-named-exports": ["error", commonOptions],
    "perfectionist/sort-named-imports": ["error", commonOptions],
    "perfectionist/sort-object-types": [
        "error",
        {
            groups: ["index-signature", "property", "method"],
            type: "unsorted",
        },
    ],
    "perfectionist/sort-objects": ["error", commonOptions],
    "perfectionist/sort-sets": ["error", commonOptions],
    "perfectionist/sort-switch-case": ["error", commonOptions],
    "perfectionist/sort-union-types": [
        "error",
        {
            ...commonOptions,
            groups: [
                "conditional",
                "function",
                "import",
                "intersection",
                "keyword",
                "literal",
                "named",
                "object",
                "operator",
                "tuple",
                "union",
                "nullish",
            ],
        },
    ],
    "perfectionist/sort-variable-declarations": ["error", commonOptions],
} satisfies Partial<Rules>;

const defaultRules: {
    [K in keyof Rules]-?: NonNullable<Linter.RulesRecord[K]>;
} = {
    ...errorDetection,
    ...codeHealth,
    ...consistency,
    ...deprecated,
    ...coveredByTypescript,
    ...coveredByOtherPlugins,
    ...considerInFuture,
    ...perfectionistRules,
    ...disabled,
};

export default defaultRules;
